In [1]:
import tensorflow as tf

C:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print(tf.__version__)

1.11.0


In [3]:
hello = tf.constant("Hello")
world = tf.constant("world")

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [10]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [11]:
print(result)

b'Helloworld'


In [13]:
a = tf.constant(10)
b = tf.constant(20)

with tf.Session() as sess:
    result = sess.run(a+b)
print(result)

30


In [14]:
const = tf.constant(10)
fill_mat = tf.fill((4,4),10)
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))
myrandn = tf.random_normal((4,4), mean = 0, stddev = 1.0)
myrandu = tf.random_uniform((4,4), minval = 0, maxval = 1)



In [15]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

sess = tf.InteractiveSession()

for op in my_ops:
    print(sess.run(op))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.4876617   0.42724097  0.36455435  0.21397333]
 [-2.9478872   2.4088821   0.17171226 -0.5757485 ]
 [ 0.1315941   0.5117046   0.21429588  0.19005874]
 [ 0.4285153   0.08212587 -0.19068123  0.40619615]]


[[0.42278206 0.20813894 0.69242024 0.87756574]
 [0.78208244 0.7602769  0.24809551 0.21833861]
 [0.47340834 0.39603376 0.40112138 0.7022145 ]
 [0.36276126 0.77555454 0.12166905 0.16944921]]




In [16]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

sess = tf.InteractiveSession()

for op in my_ops:
    print(op.eval())
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.8037659   1.4488392  -1.1788561   0.69096446]
 [-1.0801523   1.2414953   0.24964087 -0.9366304 ]
 [-0.7938877  -1.6728928   0.29066202 -1.0485456 ]
 [ 0.25008866  0.72337145  3.16713    -0.94475645]]


[[0.11912465 0.6636987  0.84912586 0.20892298]
 [0.49393857 0.29980266 0.27529073 0.1400634 ]
 [0.38869023 0.302544   0.50791526 0.46270597]
 [0.58376    0.12115145 0.6699884  0.6592995 ]]




C:\Anaconda\lib\site-packages\tensorflow\python\client\session.py:1662: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [24]:
a = tf.constant([[1,2],[2,3]])
b = tf.constant([[10], [20]])



result = tf.matmul(a,b)


In [25]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [26]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [27]:
result.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [22]:
with tf.Session() as sess:
    print(sess.run(result))
    

[[50]
 [80]]


In [28]:
result.eval()

array([[50],
       [80]])